# Project Identity
sonar.projectKey=TanyaRoy1708_ecs-deployment-devopstoolbox
sonar.projectName=ECS Project (DevOps Toolbox)
sonar.projectVersion=1.0

# SonarCloud Configuration
sonar.organization=tanyaroy1708
sonar.host.url=https://sonarcloud.io

# Source & Test paths
sonar.sources=.
sonar.tests=tests/
sonar.exclusions=tests/**,**/__pycache__/**,**/*.pyc,static/**,templates/**,.pytest_cache/**

# Language
sonar.language=py
sonar.python.version=3.11

# Reports
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=test-results.xml

# -- SCM -----------------------------------------------------------------------
sonar.scm.provider=git
